### ISSUE TITLE
Node.js 16 actions are deprecated.

### ISSUE THREAD

**Issue by yuliia-sukhova** [zoexx/github-action-json-file-properties#7]
I'm receiving a warning:

`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: zoexx/github-action-json-file-properties@release. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.`

@zoexx Would you please upgrade the Node.js version?

**Comment by zoexx** [comment]
hello @yuliia-sukhova ,I've upgraded the project : )
